import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react';
import Link from 'next/link';
import { getCookie } from '../utils/signed_transaction';
import { useEffect } from 'react';
import { Dialog, Transition } from '@headlessui/react';
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false;

import SigninRegister from '../components/SigninRegister';
import PictureGrid from '../components/PictureGrid';
import PictureUpload from '../components/PictureUpload';
import TitleBar from '../components/TitleBar';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [user, setUser] = useState<string | undefined>(undefined);
  const [picturesOwner, setPicturesOwner] = useState(null);

  useEffect(() => {
    setUser(getCookie("account-name"));
  }, []);

  return (
    <>
      <Head>
        <title>Kadena Photos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TitleBar user={user} setUser={setUser}/>
      <main className={styles.main}>
        {user ?
         <div className="flex flex-row">
            <p>Hello {user}</p>
            <Link href="/admin">Admin</Link>
         </div>
        :
          <div className={styles.description}>
            <SigninRegister setUser={setUser} />
          </div>
        }

        { user &&
          <div>
            <PictureUpload accountName={user}/>
            <PictureGrid accountName={user}/>
          </div>
        }


      </main>
    </>
  )
}
