import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react';
import Link from 'next/link';
import { getCookie } from '../utils/signed_transaction';
import { useEffect } from 'react';
import { Dialog, Transition } from '@headlessui/react';
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false;

import SigninRegister from '../components/SigninRegister';
import PictureGrid from '../components/PictureGrid';
import PictureUpload from '../components/PictureUpload';
import TitleBar from '../components/TitleBar';
import UserListing from '../components/UserListing';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [user, setUser] = useState<string | undefined>(undefined);
  const [pictures, setPictures] = useState([]);
  const [picturesOwner, setPicturesOwner] = useState<string | undefined>(undefined);

  useEffect(() => {
    let user = getCookie("account-name");
    setUser(user);
    setPicturesOwner(user);
  }, []);

  return (
    <>
      <Head>
        <title>PactPics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TitleBar user={user} setUser={setUser}/>
      <main className={styles.main}>
        { user &&
          <div className="w-full">
            <UserListing user={user} picturesOwner={picturesOwner} setPicturesOwner={setPicturesOwner}/>
            <PictureUpload accountName={user} pictures={pictures} setPictures={setPictures}/>
            <PictureGrid accountName={picturesOwner} pictures={pictures} setPictures={setPictures} user={user}/>
          </div>
        }


      </main>
    </>
  )
}
